### ISSUE TITLE
Regular Update of coin-miners.txt

### ISSUE THREAD

**Issue by Green-Leaves500** [brave/adblock-lists#1329]
Does coin-miners.txt list gets update regularly ? And does it turned on by default on Shields ?

**Comment by pes10k** [comment]
I dont think so.  In fact, i think we mostly rely on other malware / resource abuse lists at this point.  @ryanbr @antonok-edm should we delete it all togehter (and try and get whatever uniquely useful rules are still in it accepted in other lists)?

**Comment by ryanbr** [comment]
Its no longer in use @Green-Leaves500 cc: @pes10k 

All the coin mining filters are included in Easyprivacy, and then eventually pruned off since most of the coin servers were removed (dead domains). Most coin servers and scripts have been dead/non-working now, other than very selective mining sites.

1. [Easyprivacy coin domains](https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_trackingservers.txt#L3077)
1. [Easyprivacy coin generic](https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_general.txt#L3587)

I expect over time the coin mining list section in Easyprivacy will get smaller

**Comment by pes10k** [comment]
oh! Can we delete https://github.com/brave/adblock-lists/blob/master/coin-miners.txt then?
