### ISSUE TITLE
The Browser is having problems with the "Do-not Track Policies"

### ISSUE THREAD

**Issue by Soumik0007** [brave/adblock-lists#530]
The Browser is having problems with the "Do-Not Track Policies".Please do something brave team.We want you to be the best browser in the game.

**Comment by pes10k** [comment]
@Soumik0007 can you say more about the problem you're seeing?

1. Brave doesn't send a DNT header bc we don't think it improves privacy for users.  We are instead focusing on supporting what we see as the likely successor, [GPC](https://globalprivacycontrol.github.io/gpc-spec/).
2. Additionally, since the spec is effectively dead, we don't have plans to reenable it.
3. Finally, DNT is often used as a fingerprinting bit, so unless we learn of some way that it actually concretely improves privacy (instead of more just wishing to do so) we don't have any plans to reenable.

If you have any questions or think I've missed anything, please follow up with a comment below if you'd like.  In th meantime though, im going to close this issue as not actionable.

**Comment by Soumik0007** [comment]
Ohh!!! Thanks!!! I didn't know about that. By the way,keep up the good work.
