### ISSUE TITLE
Please don't block Developer Tools (sentry.io)

### ISSUE THREAD

**Issue by robd003** [brave/adblock-lists#877]
Sentry.io is a tool for developers to receive bug reports from broken web apps. Blocking Sentry hurts users.

At a minimum please have an option within Shields at a global level to not block error reporting tools.

**Comment by pes10k** [comment]
I do not think our users want a "block everything but error reporting tools" mode.  Since Brave's browsers serve our users first and foremost, i do not expect we will create a feature like this (setting aside the fact that, in behavior, it is difficult to impossible to distinguish "error reporting tools" from tracking scripts)
